security.yml
// tambe cal posar a true     csrf_protection: false    del fitxer config.yml

original    

firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: true
            security: true

modificat


firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout: true
            anonymous: true
            security: true