backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

extranet:
    resource: "@BackendBundle/Resources/config/extranet/routing.yml"
    prefix:   /extranet


usuaris:
    resource: "@UsuarisBundle/Resources/config/routing.yml"
    prefix:   /

calendari:
    resource: "@CalendariBundle/Controller/"
    type:     annotation
    prefix:   /

client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

activitat:
    resource: "@ActivitatBundle/Resources/config/routing.yml"
    prefix:   /

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
