security:
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_ADMIN:             ROLE_USER
        ROLE_SUPER_ADMIN:       ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: true
            security: true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: ROLE_ADMIN }
        - { path: ^/resetting$, role: ROLE_ADMIN }
        - { path: /extranet*, roles: ROLE_ADMIN }
        - { path: /admin*, roles: ROLE_ADMIN }
        - { path: /extranet/calendari/visualitzar*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       