security:
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are not using acl then this line must be uncommented
    providers:
        fos_userbundle:
            id: fos_user.user_manager
    firewalls:
        admin:
            pattern:            /admin(.*)
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    true
                check_path:     /admin/login_check
                ##failure_path:   null
            logout:
                path:    /admin/logout
                target:  /extranet/portada
            anonymous:    true
            logout: true
            remember_me:
                key:      9034895c8e6816cad3f8fc4d3171bce10
                lifetime: 3600
                path:     /extranet/portada
                domain:   ~
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /extranet/portada
                use_referer: true
            logout:
                path: /logout
                target: /extranet/portada
            anonymous: true
            security: true
            logout: true
        ##login_firewall:
        ##  pattern:    ^/login$
        ##     anonymous:  ~ 












    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: ROLE_ADMIN }
        - { path: ^/resetting$, role: ROLE_ADMIN }
        - { path: /extranet/calendari/activitat/visualitzar*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /extranet/calendari/email*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /extranet*, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: /admin*, roles: [ROLE_USER, ROLE_ADMIN] }
    acl:
        connection: default

