parameters:
    # ... other parameters
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap
    # optionally use a custom MaskBuilder

services:
#    usuaris.example:
#        class: %usuaris.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     