parameters:
#    usuaris.example.class: vitaworke3\UsuarisBundle\Example

services:
#    usuaris.example:
#        class: %usuaris.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
