extranet_inici:
    pattern: /
    defaults: { _controller:BackendBundle:Extranet:inici }
extranet_portada:
    pattern: /portada
    defaults: { _controller:BackendBundle:Extranet:portada }
extranet_perfil:
   pattern: /perfil
   defaults: { _controller:BackendBundle:Extranet:perfil }

extranet_activitat:
    pattern: /activitat
    defaults: { _controller:ActivitatBundle:Activitat:Activitat }
extranet_activitat_filtre:
    pattern: /activitat/select/{idformador}
    defaults: { _controller:ActivitatBundle:Activitat:ActivitatFiltre }    
extranet_activitat_nova:
    pattern: /activitat/nova
    defaults: { _controller:ActivitatBundle:Activitat:ActivitatNova }
extranet_activitat_editar:
    pattern: /activitat/editar/{id}
    defaults: { _controller:ActivitatBundle:Activitat:ActivitatEditar }
extranet_preview:
    pattern: /activitat/preview/{id}
    defaults: { _controller:ActivitatBundle:Activitat:ActivitatPreview }

extranet_calendari:
    pattern: /calendari
    defaults: { _controller:CalendariBundle:Calendari:Calendari }
extranet_calendari_nou:
    pattern: /calendari/nou
    defaults: { _controller:CalendariBundle:Calendari:CalendariNou }
extranet_calendari_editar:
    pattern: /calendari/editar/{id}
    defaults: { _controller:CalendariBundle:Calendari:CalendariEditar }
extranet_calendari_visualitzar:
    pattern: /calendari/visualitzar/{id}
    defaults: { _controller:CalendariBundle:Calendari:CalendariVisualitzar }
extranet_calendari_activitat_visualitzar:
    pattern: /calendari/activitat/visualitzar/{id}
    defaults: { _controller:CalendariBundle:Calendari:CalendariActivitatVisualitzar }
extranet_calendari_valorar:
    pattern: /calendari/valorar/{id}
    defaults: { _controller:CalendariBundle:Calendari:CalendariValorar }
extranet_calendari_email:
    pattern: /calendari/email/{id}
    defaults: { _controller:CalendariBundle:Calendari:CalendariEmail }

extranet_planning:
    pattern: /planning/client
    defaults: { _controller:CalendariBundle:Calendari:Planning }
extranet_planning_filtre:
    pattern: /planning/{idany}/{idmes}/{idempresa}
    defaults: { _controller:CalendariBundle:Calendari:PlanningFiltre }
extranet_planning_empresa:
    pattern: /planning/empresa
    defaults: { _controller:CalendariBundle:Calendari:PlanningEmpresa }
extranet_calendari_nou_planning:
    pattern: /calendari/{accion}/{idempresa}/{id}/{idany}/{idmes}/{iddia}/{idcalendari}
    defaults: { _controller:CalendariBundle:Calendari:CalendariNouPlanning }


extranet_client:
    pattern: /client
    defaults: { _controller:ClientBundle:Client:Client }
extranet_client_filtre:
    pattern: /client/select/{idassociat}
    defaults: { _controller:ClientBundle:Client:ClientFiltre }
extranet_client_nou:
    pattern: /client/nou
    defaults: { _controller:ClientBundle:Client:ClientNou }
extranet_client_editar:
    pattern: /client/editar/{id}
    defaults: { _controller:ClientBundle:Client:ClientEditar }




extranet_empresa:
    pattern: /empresa
    defaults: { _controller:ClientBundle:Empresa:Empresa }
extranet_empresa_nova:
    pattern: /empresa/nova
    defaults: { _controller:ClientBundle:Empresa:EmpresaNova }
extranet_empresa_editar:
    pattern: /empresa/editar/{id}
    defaults: { _controller:ClientBundle:Empresa:EmpresaEditar }
extranet_empresa_filtre:
    pattern: /empresa/select/{ididioma}/{idtemplate}/{idresponsable}
    defaults: { _controller:ClientBundle:Empresa:EmpresaFiltre }



extranet_grup:
    pattern: /grup
    defaults: { _controller:ClientBundle:Grup:Grup }
extranet_grup_filtre:
    pattern: /grup/select/{idassociat}
    defaults: { _controller:ClientBundle:Grup:GrupFiltre }
extranet_grup_nou:
    pattern: /grup/nou
    defaults: { _controller:ClientBundle:Grup:GrupNou }
extranet_grup_editar:
    pattern: /grup/editar/{id}
    defaults: { _controller:ClientBundle:Grup:GrupEditar }
extranet_Grup_filtre:
    pattern: /grup/select/{idassociat}/{ididioma}/{idtemplate}/{idresponsable}
    defaults: { _controller:ClientBundle:Grup:GrupFiltre }


extranet_comite:
    pattern: /comite
    defaults: { _controller:ClientBundle:Comite:Comite }
extranet_comite_nou:
    pattern: /comite/nou
    defaults: { _controller:ClientBundle:Comite:ComiteNou}
extranet_comite_editar:
    pattern: /comite/editar/{id}
    defaults: { _controller:ClientBundle:Comite:ComiteEditar}

extranet_formador:
    pattern: /formador
    defaults: { _controller:ClientBundle:Formador:Formador }
extranet_formador_filtre:
    pattern: /formador/select/{idcomite}
    defaults: { _controller:ClientBundle:Formador:FormadorFiltre }
extranet_formador_nou:
    pattern: /formador/nou
    defaults: { _controller:ClientBundle:Formador:FormadorNou }
extranet_formador_editar:
    pattern: /formador/editar/{id}
    defaults: { _controller:ClientBundle:Formador:FormadorEditar }

extranet_template:
    pattern: /template
    defaults: { _controller:ClientBundle:Template:Template }
extranet_template_filtre:
    pattern: /template/{idempresa}
    defaults: { _controller:ClientBundle:Template:TemplateFiltre }
extranet_template_editar:
    pattern: /template2/editar/{id}
    defaults: { _controller:ClientBundle:Template:TemplateEditar }
extranet_template_nou:
    pattern: /template2/nou
    defaults: { _controller:ClientBundle:Template:TemplateNou }



extranet_usuaris:
    pattern: /usuaris
    defaults: { _controller:UsuarisBundle:Usuaris:Usuaris }
extranet_usuaris_nou:
    pattern: /usuaris/registre
    defaults: { _controller:UsuarisBundle:Usuaris:UsuarisNou }
extranet_usuaris_editar:
    pattern: /usuaris/editar/{id}
    defaults: { _controller:UsuarisBundle:Usuaris:UsuarisEditar }
extranet_usuaris_reset:
    pattern: /usuaris/reset/{id}
    defaults: { _controller:UsuarisBundle:Usuaris:UsuarisReset}
