parameters:
#    client.example.class: vitaworke3\ClientBundle\Example

services:
#    client.example:
#        class: %client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
