extranet_inici:
    pattern: /
    defaults: { _controller:BackendBundle:Extranet:inici }
extranet_portada:
    pattern: /portada
    defaults: { _controller:BackendBundle:Extranet:portada }
extranet_activitat_nova:
    pattern: /activitat/nova
    defaults: { _controller:BackendBundle:Extranet:ActivitatNova }
extranet_activitat:
    pattern: /activitat
    defaults: { _controller:BackendBundle:Extranet:Activitat }
_extranet_activitat:
    pattern: /activitat/
    defaults: { _controller:BackendBundle:Extranet:Activitat }
extranet_activitat_editar:
    pattern: /activitat/editar/{id}
    defaults: { _controller:BackendBundle:Extranet:ActivitatEditar }
extranet_perfil:
   pattern: /perfil
   defaults: { _controller:BackendBundle:Extranet:perfil }
extranet_calendari:
    pattern: /calendari
    defaults: { _controller:BackendBundle:Extranet:Calendari }
extranet_calendari_nou:
    pattern: /calendari/nou
    defaults: { _controller:BackendBundle:Extranet:CalendariNou }
extranet_calendari_editar:
    pattern: /calendari/editar/{id}
    defaults: { _controller:BackendBundle:Extranet:CalendariEditar }
extranet_client:
    pattern: /client
    defaults: { _controller:BackendBundle:Extranet:Client }
extranet_client_nou:
    pattern: /client/nou
    defaults: { _controller:BackendBundle:Extranet:ClientNou }
extranet_client_editar:
    pattern: /client/editar/{id}
    defaults: { _controller:BackendBundle:Extranet:ClientEditar }
extranet_calendari_activitat_visualitzar:
    pattern: /calendari/visualitzar/{id}
    defaults: { _controller:BackendBundle:Extranet:CalendariActivitatVisualitzar }
extranet_task:
    pattern: /task
    defaults: { _controller:ActivitatBundle:Task:task }
extranet_task_nova:
    pattern: /task/nova
    defaults: { _controller:ActivitatBundle:Task:new }

